### ISSUE TITLE
Tests failing on Node.js 6

### ISSUE THREAD

**Issue by jacksonrayhamilton** [glebmachine/postcss-cachebuster#3]
When running the tests on Node.js 6.2.0, I get the following error:

```
(node:7533) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

...

  1) postcss-cachebuster Skip unresolved images:
     TypeError: Path must be a string. Received undefined
      at assertPath (path.js:7:11)
      at Object.dirname (path.js:1324:5)
      at Object.dirname (node_modules/canonical-path/index.js:13:29)
      at resolveUrl (index.js:54:50)
      at index.js:106:25
      at RegExp.[Symbol.replace] (native)
      at String.replace (native)
      at walkThroughtDeclarations (index.js:94:45)
      at node_modules/postcss/lib/container.js:94:28
      at node_modules/postcss/lib/container.js:81:26
```

No such error on Node.js 5.11.1, though.

Using `npm ls` reveals there are a few old versions of `graceful-fs` in the dependency tree. Not sure which is the culprit in this case.

**Comment by glebmachine** [comment]
Ok, will check it soon)
